field.formatter.settings.svg_sanitizer:
  type: mapping
  label: 'SVG Sanitizer settings'
  mapping:
    allowedattrs:
      type: string
      label: 'Allowed attributes'
    allowedtags:
      type: string
      label: 'Allowed tags'
